import type { Account, Settings } from '@/types/entities'

export { DEFAULT_CATEGORIES } from '@/constants/transactionCategories'

const now = () => new Date().toISOString()

/** §6 default accounts: Cash, Bank Account, Credit Card, UPI Wallet,
 * Emergency Fund. All start at a zero balance; the user sets an opening
 * balance during onboarding or their first edit. */
export const DEFAULT_ACCOUNTS: Account[] = [
  {
    id: 'acc-cash',
    name: 'Cash',
    type: 'cash',
    icon: 'Banknote',
    color: '#16A34A',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
    currency: 'INR',
  },
  {
    id: 'acc-bank',
    name: 'Bank Account',
    type: 'bank',
    icon: 'Landmark',
    color: '#2563EB',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
    currency: 'INR',
  },
  {
    id: 'acc-credit-card',
    name: 'Credit Card',
    type: 'creditCard',
    icon: 'CreditCard',
    color: '#9333EA',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
    currency: 'INR',
  },
  {
    id: 'acc-upi',
    name: 'UPI Wallet',
    type: 'upiWallet',
    icon: 'Smartphone',
    color: '#0D9488',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
    currency: 'INR',
  },
  {
    id: 'acc-emergency-fund',
    name: 'Emergency Fund',
    type: 'emergencyFund',
    icon: 'ShieldCheck',
    color: '#CA8A04',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: true,
    isArchived: false,
    createdAt: now(),
    updatedAt: now(),
    currency: 'INR',
  },
]

/** §5 Settings Entity defaults. `onboardingCompleted` isn't in the spec's
 * field list — flagged as an added field; see build notes. */
export const DEFAULT_SETTINGS: Settings = {
  id: 'active',
  theme: 'system',
  themePreset: 'classic',
  currency: 'INR',
  currencyDisplay: 'lakh-crore',
  dateFormat: 'DD/MM/YYYY',
  language: 'en',
  defaultView: 'dashboard',
  budgetMonthStart: 1,
  backupFrequency: 'off',
  firstDayOfWeek: 0,
  animationEnabled: true,
  hapticFeedback: false,
  compactMode: false,
  appLockEnabled: false,
  appLockPinHash: null,
  appLockTimeoutMinutes: 5,
  developerMode: false,
  accentColor: '#0F4D45',
  chartStyle: 'rounded',
  cardStyle: 'elevated',
  animationLevel: 'normal',
  density: 'comfortable',
  cornerRadius: 'medium',
  fontFamily: 'inter',
  dashboardLayout: 'cards',
  onboardingCompleted: false,
  sampleDataRequested: false,
  lastBackupAt: null,
}
