import type { CategoryDef } from './types'

/**
 * Income taxonomy — the new dynamic income list. `cat-salary` keeps its
 * original id so historical income transactions resolve unchanged; the rest
 * are new ids. Two illustrative subcategory sets (Salary → Monthly
 * Salary/Overtime/Incentives, Investment Income → Dividends/Capital
 * Gains/Mutual Funds/Fixed Deposit Interest) demonstrate the optional
 * two-level selection.
 */
export const INCOME_CATEGORY_DEFS: CategoryDef[] = [
  {
    id: 'cat-salary',
    name: 'Salary',
    icon: 'Wallet',
    color: '#10B981',
    kind: 'income',
    keywords: ['salary', 'paycheck', 'stipend'],
    subcategories: [
      {
        id: 'cat-salary-monthly',
        name: 'Monthly Salary',
        icon: 'Wallet',
        color: '#10B981',
        kind: 'income',
        keywords: [],
      },
      {
        id: 'cat-salary-overtime',
        name: 'Overtime',
        icon: 'Clock',
        color: '#10B981',
        kind: 'income',
        keywords: [],
      },
      {
        id: 'cat-salary-incentives',
        name: 'Incentives',
        icon: 'Sparkles',
        color: '#10B981',
        kind: 'income',
        keywords: [],
      },
    ],
  },
  {
    id: 'cat-bonus',
    name: 'Bonus',
    icon: 'Sparkles',
    color: '#F59E0B',
    kind: 'income',
    keywords: ['bonus', 'incentive'],
  },
  {
    id: 'cat-freelance',
    name: 'Freelance',
    icon: 'Briefcase',
    color: '#0EA5E9',
    kind: 'income',
    keywords: ['freelance', 'gig', 'client payment'],
  },
  {
    id: 'cat-business',
    name: 'Business Income',
    icon: 'Store',
    color: '#6366F1',
    kind: 'income',
    keywords: ['business', 'sales', 'revenue'],
  },
  {
    id: 'cat-investment',
    name: 'Investment Income',
    icon: 'TrendingUp',
    color: '#14B8A6',
    kind: 'income',
    keywords: ['investment', 'mutual fund', 'capital gain'],
    subcategories: [
      {
        id: 'cat-investment-dividends',
        name: 'Dividends',
        icon: 'Coins',
        color: '#14B8A6',
        kind: 'income',
        keywords: [],
      },
      {
        id: 'cat-investment-capital-gains',
        name: 'Capital Gains',
        icon: 'TrendingUp',
        color: '#14B8A6',
        kind: 'income',
        keywords: [],
      },
      {
        id: 'cat-investment-mutual-funds',
        name: 'Mutual Funds',
        icon: 'PiggyBank',
        color: '#14B8A6',
        kind: 'income',
        keywords: [],
      },
      {
        id: 'cat-investment-fd-interest',
        name: 'Fixed Deposit Interest',
        icon: 'Percent',
        color: '#14B8A6',
        kind: 'income',
        keywords: [],
      },
    ],
  },
  {
    id: 'cat-interest',
    name: 'Interest',
    icon: 'Percent',
    color: '#A855F7',
    kind: 'income',
    keywords: ['interest'],
  },
  {
    id: 'cat-dividend',
    name: 'Dividend',
    icon: 'Coins',
    color: '#EC4899',
    kind: 'income',
    keywords: ['dividend'],
  },
  {
    id: 'cat-rental',
    name: 'Rental Income',
    icon: 'Home',
    color: '#F97316',
    kind: 'income',
    keywords: ['rent received', 'rental', 'landlord'],
  },
  {
    id: 'cat-cashback',
    name: 'Cashback & Rewards',
    icon: 'BadgePercent',
    color: '#84CC16',
    kind: 'income',
    keywords: ['cashback', 'rewards', 'points'],
  },
  {
    id: 'cat-refund',
    name: 'Refund',
    icon: 'RotateCcw',
    color: '#22C55E',
    kind: 'income',
    keywords: ['refund', 'reimbursement', 'money back'],
  },
  {
    id: 'cat-gift',
    name: 'Gift Received',
    icon: 'Gift',
    color: '#E879F9',
    kind: 'income',
    keywords: ['gift received'],
  },
  {
    id: 'cat-pension',
    name: 'Pension',
    icon: 'Umbrella',
    color: '#64748B',
    kind: 'income',
    keywords: ['pension', 'annuity'],
  },
  {
    id: 'cat-gov-benefits',
    name: 'Government Benefits',
    icon: 'Landmark',
    color: '#0D9488',
    kind: 'income',
    keywords: ['government benefit', 'subsidy', 'welfare'],
  },
  {
    id: 'cat-tax-refund',
    name: 'Tax Refund',
    icon: 'ReceiptText',
    color: '#34D399',
    kind: 'income',
    keywords: ['tax refund', 'itr refund'],
  },
  {
    id: 'cat-other-income',
    name: 'Other Income',
    icon: 'PiggyBank',
    color: '#78716C',
    kind: 'income',
    keywords: ['income', 'received', 'credited'],
  },
]
